name: Notion
on:
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:
jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          yarn install --frozen-lockfile
      - run: |
          bash scripts/notion2md.sh
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      - continue-on-error: true
        run: |
          yarn run fix
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "chore: auto notion update"
          git push
