name: Resume
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  resume:
    name: Resume PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            cd data
            pdflatex resume.tex
      # - if: github.event_name == 'push'
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Apply Resume PDF
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: chore: apply resume.pdf
