name: Secrets
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/secrets.yml
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONCURRENCY: 10
          DRY_RUN: false
          SECRETS: |
            ACCESS_TOKEN
            DOCKER_PASSWORD
            NPM_TOKEN
          REPOSITORIES: |
            shunkakinoki/codespaces
            shunkakinoki/configurations
            shunkakinoki/dotfiles
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
